name: EC2 Connection
# Smoke test for deployment. Logs current github action repo commit hash into remote server.
on:
  push:
    branches:
      - main
jobs:
  deployment:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checks out this branch
        uses: actions/checkout@v3
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          envs: SHA
          script: |
            echo "$SHA" >> fromgithubaction.log
